
version: '3.6'
services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influxdb_config:/etc/influxdb2
      - /etc/localtime:/etc/localtime:ro

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
      
#volumes:
  #grafana: {}
  #influxdb_data: {}
  #influxdb_config: {}